### ISSUE TITLE
windows下google图片无法爬取

### ISSUE THREAD

**Issue by terminats17** [sczhengyabin/Image-Downloader#10]
刚开始用VPN, 无法爬取
然后我又开通了个硅谷的阿里服务器，2016server，还是无法爬取。
ping google和网页浏览google都没有问题

**Comment by sczhengyabin** [comment]
百度和必应是正常的呃？

**Comment by terminats17** [comment]
是exe，百度和必应是正常的

**Comment by sczhengyabin** [comment]
@terminats17 
我在win10下连接PPTP的VPN测试，无法复现你说的问题。
请注意允许exe的网络访问。

如果还不行，请说明：
1. 使用的具体的操作系统的版本
2. VPN的连接类型
3. 运行程序的截图

谢谢
