### ISSUE TITLE
不支持中文关键字搜索

### ISSUE THREAD

**Issue by ujsyehao** [sczhengyabin/Image-Downloader#12]

**Comment by sczhengyabin** [comment]
你好，中文关键字支持的，如果你用windows版本直接可行。Linux版本可能由于Qt与桌面输入法的对接问题导致无法输入，但可从其他编辑器中复制中文关键字粘贴到搜索框使用。另外还可以使用文本列表

**Comment by ujsyehao** [comment]
@sczhengyabin 你好，粘贴关键字后，它提升报错：
![229](https://user-images.githubusercontent.com/17454232/47710457-c46fb000-dc6d-11e8-899d-8c514315f24e.png)
另外，还有一个问题，它只能支持最多2000张图片吗
