### ISSUE TITLE
Can not download images from Google

### ISSUE THREAD

**Issue by Qjizhi** [sczhengyabin/Image-Downloader#15]
$ python3 image_downloader.py "stroller on street" -e Google

Scraping From Google Image Search ...

Keywords:  stroller on street
Number:  100
Face Only:  False
Safe Mode:  False
Query URL:  https://www.google.com/search?tbm=isch&hl=en&q=stroller%20on%20street&safe=off

== 0 out of 0 crawled images urls will be used.

Finished.

it works with Bing and Baidu, but the search results with this two engines are not satisfied, how can I fix this? Thanks!

**Comment by sczhengyabin** [comment]
@Qjizhi Not sure why it didn't work.
Have you tried the windows packed exe version? Did it work?

**Comment by zfxxfeng** [comment]
If you can't get the urls，you can uncomment the time.sleep(10) in crawler.py (line 56).

**Comment by sczhengyabin** [comment]
@Qjizhi It could be the situation that your internet connection is relative slow, so that the page may not load completely when code checking the urls. 
@zfxxfeng Thanks for pointing that out.
