### ISSUE TITLE
win10命令行下代理服务器下载google图片有问题

### ISSUE THREAD

**Issue by gqf126** [sczhengyabin/Image-Downloader#20]
系统：win10，命令行模式，browser为chrome，无法使用代理服务器下载google图片。
Traceback:
Message: no such element: Unable to locate element: {"method":"id","selector":"smb"}
在此过程中网络配置正确，在响应的chrome窗口中可以看到打开google image链接并搜索到相应的图片。

能否帮忙看一下这个问题？
谢谢

**Comment by sczhengyabin** [comment]
@gqf126 Google 最近修改了图片搜索的页面，目前还没有时间来做这个更新，只能暂时使用bing和百度

**Comment by sczhengyabin** [comment]
@gqf126 可以测试下最新的提交看看是否可以使用

**Comment by gqf126** [comment]
谢谢，可以用了
