### ISSUE TITLE
无法用GUI下载百度图片

### ISSUE THREAD

**Issue by Xelawk** [sczhengyabin/Image-Downloader#30]
GUI模式下选择百度时，无法勾选爬取模式

**Comment by mapattacker** [comment]
See https://github.com/sczhengyabin/Image-Downloader/issues/29

**Comment by kating37** [comment]
我的也出现了这个问题

**Comment by sczhengyabin** [comment]
@Xelawk 百度默认使用api爬取（更快），可在代码中改为浏览器模式

**Comment by kating37** [comment]
谢谢，我去看啦，可以爬百度的图片啦





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sczhengyabin/Image-Downloader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月6日(星期二) 晚上8:43
收件人:&nbsp;"sczhengyabin/Image-Downloader"<Image-Downloader@noreply.github.com&gt;;
抄送:&nbsp;"KAT"<2921044040@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [sczhengyabin/Image-Downloader] 无法用GUI下载百度图片 (#30)





 
Closed #30.
