### ISSUE TITLE
Unhandled Python exception when chosing .txt file

### ISSUE THREAD

**Issue by ArsenLuca** [sczhengyabin/Image-Downloader#5]
![image](https://cloud.githubusercontent.com/assets/23271554/25475836/b4874e1a-2b6a-11e7-9731-0fb4d34582d1.png)
whenever I click the chose .txt button and chose a .txt file, exception happens as the picture

**Comment by sczhengyabin** [comment]
Thanks for opening the issue !
Bug fixed.
Comes from one api defference between pyqt4 and pyqt5, which I forget to test before I release the latest version.
