### ISSUE TITLE
关于下载您的软件windows配置的问题

### ISSUE THREAD

**Issue by helloxueen** [sczhengyabin/Image-Downloader#6]
您好，博主，现在我已经把要下载的QT5和Python3都下载了，但是后面的执行和copy步骤看不懂，能否详细说明一下？

**Comment by sczhengyabin** [comment]
我会抽时间写一个中文版本的readme
目前版本的步骤没问题，许多人都照着这个搭建起来了的，你可以再理解、尝试下，不行等我中文版

**Comment by sczhengyabin** [comment]
已添加中文README
