### ISSUE TITLE
Missing dependencies for SOCKS support

### ISSUE THREAD

**Issue by hewj03** [sczhengyabin/Image-Downloader#7]
When downloading from Google, i setup proxy as 
            proxy_type = "socks5"
            proxy = "127.0.0.1:1080"

Download failed, error message is:

## Fail:  http://bpic.ooopic.com/11/05/28/49b1OOOPIC4f.jpg!/fw/780/quality/90/unsharp/true/compress/true  ('Missing dependencies for SOCKS support.',)

Do you know why? Thanks.

**Comment by sczhengyabin** [comment]
@hewj03 
pip install requests[socks]

**Comment by hewj03** [comment]
E:\>pip install requests[socks]
Requirement already satisfied: requests[socks] in c:\python36\lib\site-packages
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in c:\python36\lib\site-packages (from requests[socks])

So they are already installed.

**Comment by hewj03** [comment]
This happens when i'm using Win10.

In ubuntu, it is ok. I can download images from google using socks4 proxy.

**Comment by sczhengyabin** [comment]
@hewj03 Not sure what happend.
Please recheck the python installation. Or try using Anaconda environment in windows instead.
However, the alternative way to use proxy in win 10, is to set the application proxy to None while set the system-wide proxy to your own proxy. The system-wide proxy will also affect on this "_Image-Downloader_" .

**Comment by hewj03** [comment]
ok, thanks a lot.
