### ISSUE TITLE
GUI版最大下载图片数量只能下2000？

### ISSUE THREAD

**Issue by whaozl** [sczhengyabin/Image-Downloader#9]

**Comment by sczhengyabin** [comment]
@whaozl 是的，一个关键词出来的图片，百度的最多，也不超过2000个，所以就设置了2000的上限。

**Comment by whaozl** [comment]
谷歌的会超过2000呢 嘿嘿 比如我想爬cat的图片 谷歌可以出来好多

**Comment by sczhengyabin** [comment]
@whaozl 你确定人工数过数量的？我记得虽然可以一直翻，但是最终也只有几百张

**Comment by whaozl** [comment]
我刚才确定过了 确实是2000 感谢哈 那互联网上的图片就这么多 几百张  我因为很多来着

**Comment by whaozl** [comment]
@sczhengyabin 
https://www.google.com/search?tbm=isch&hl=en&q=%E5%86%B0%E9%94%90%E6%9C%97%E5%A7%86%E9%A2%84%E8%B0%83%E9%85%92%28%E6%A9%99%E5%91%B3%29275ml%E7%93%B6%E8%A3%85&safe=on

这个用您软件只能吓到98张图片 其实不止 可以一直浏览下去

**Comment by sczhengyabin** [comment]
![image](https://user-images.githubusercontent.com/3861633/30148502-42328df0-93d6-11e7-98c8-8ff8ba4b3d04.png)

@whaozl 
你好，这种情况往往会在代理网速不够快的情况下发生，代码会在打开网页一定时间后检测是否有“显示更多”的按钮出来，如果没有就不会继续往下加载了。 所以要应对这种情况，要么换一个快一点的代理，要么修改代码，增加检测按钮的延时。

**Comment by whaozl** [comment]
@sczhengyabin 为什么您有这么多 我好多关键词都是99，我是直接用国外的服务器下的嘿 速度超快的 您说的检测按钮的延时可以设置吗？具体在哪里嘿?

**Comment by sczhengyabin** [comment]
@whaozl 
在crawlay.py文件，google_image_url_from_webpage的两个sleep。
